/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.Date;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import phar.db;


/**
 *
 * @author Ana
 */
public class report extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form report
     */
    public report() throws SQLException {
        initComponents();
         con = db.connect();
    }
    public report(DefaultTableModel m,String ll1,String ll2,String ll3,String rn,String cassh,String duee,String name,
            String cl,String ads,String ddatee) throws SQLException {
        initComponents();
        con = db.connect();
        ttt.setModel(m);
        l1.setText(ll1);
        l4.setText(ll1);
        l2.setText(ll2);
        l3.setText(ll3);
        rr.setText(rn);
        cash.setText(cassh);
        due.setText(duee);
        cn.setText(name);
        cell.setText(cl);
        add.setText(ads);
        ddate.setText(ddatee);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        cash = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        ddate = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        cell = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 800));

        pan.setBackground(new java.awt.Color(255, 255, 255));
        pan.setForeground(new java.awt.Color(255, 255, 255));
        pan.setLayout(null);

        ttt.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        ttt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        ttt.setAlignmentX(0.2F);
        ttt.setAlignmentY(0.2F);
        ttt.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ttt);
        if (ttt.getColumnModel().getColumnCount() > 0) {
            ttt.getColumnModel().getColumn(0).setMinWidth(25);
            ttt.getColumnModel().getColumn(0).setPreferredWidth(25);
            ttt.getColumnModel().getColumn(0).setMaxWidth(25);
            ttt.getColumnModel().getColumn(2).setPreferredWidth(100);
            ttt.getColumnModel().getColumn(3).setMinWidth(100);
            ttt.getColumnModel().getColumn(3).setPreferredWidth(100);
            ttt.getColumnModel().getColumn(3).setMaxWidth(100);
            ttt.getColumnModel().getColumn(4).setPreferredWidth(100);
            ttt.getColumnModel().getColumn(5).setPreferredWidth(100);
            ttt.getColumnModel().getColumn(6).setPreferredWidth(100);
            ttt.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        pan.add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 810, 350);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel1.setText("M/s Sardar Pharmacy ");
        pan.add(jLabel1);
        jLabel1.setBounds(370, 30, 100, 10);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel2.setText(" Amtoli, Sadar Road, Joypurhat");
        pan.add(jLabel2);
        jLabel2.setBounds(350, 40, 130, 10);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel3.setText("Md.Rafsan Zadid");
        pan.add(jLabel3);
        jLabel3.setBounds(370, 50, 80, 11);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel4.setText("Cell: 01770667694,01711239295(Owner)");
        pan.add(jLabel4);
        jLabel4.setBounds(330, 60, 170, 11);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel5.setText("Email: rafsanzadid@gmail.com");
        pan.add(jLabel5);
        jLabel5.setBounds(350, 70, 130, 11);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel6.setText("Date:");
        pan.add(jLabel6);
        jLabel6.setBounds(30, 100, 40, 11);
        pan.add(jSeparator1);
        jSeparator1.setBounds(0, 90, 1060, 10);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel7.setText("Customer Name:");
        pan.add(jLabel7);
        jLabel7.setBounds(30, 130, 80, 11);

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel8.setText("Address:");
        pan.add(jLabel8);
        jLabel8.setBounds(360, 100, 40, 11);

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel9.setText(" Cell No:");
        pan.add(jLabel9);
        jLabel9.setBounds(360, 130, 40, 11);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton2.setText("PRINT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pan.add(jButton2);
        jButton2.setBounds(620, 610, 100, 30);

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel10.setText("Receipt No:");
        pan.add(jLabel10);
        jLabel10.setBounds(610, 130, 50, 14);

        l3.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(l3);
        l3.setBounds(700, 500, 100, 20);

        l2.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(l2);
        l2.setBounds(590, 500, 90, 20);

        l1.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(l1);
        l1.setBounds(470, 500, 100, 20);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel14.setText("Grand Total: ");
        pan.add(jLabel14);
        jLabel14.setBounds(10, 510, 60, 14);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel15.setText("Cash:");
        pan.add(jLabel15);
        jLabel15.setBounds(10, 540, 30, 14);

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel16.setText("Dues:");
        pan.add(jLabel16);
        jLabel16.setBounds(10, 570, 40, 14);

        l4.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(l4);
        l4.setBounds(70, 510, 120, 20);

        rr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pan.add(rr);
        rr.setBounds(660, 130, 100, 20);

        cash.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(cash);
        cash.setBounds(40, 540, 130, 20);

        due.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(due);
        due.setBounds(40, 570, 90, 20);

        ddate.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(ddate);
        ddate.setBounds(60, 94, 130, 20);

        cn.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        pan.add(cn);
        cn.setBounds(110, 124, 180, 20);

        add.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pan.add(add);
        add.setBounds(400, 94, 420, 20);

        cell.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pan.add(cell);
        cell.setBounds(400, 124, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    
        try{
            PreparedStatement pst1=con.prepareStatement("insert into receiptrecord values(?,?,?,?,?,?,?,?)");
                    pst1.setInt(1, Integer.parseInt(rr.getText()));
                    pst1.setString(2, cn.getText());
                    pst1.setString(3, add.getText());
                    pst1.setInt(4, Integer.parseInt(cell.getText()));
                   
                    pst1.setFloat(5, Float.parseFloat(l4.getText()));
                    pst1.setFloat(6, Float.parseFloat(cash.getText()));
                    pst1.setFloat(7, Float.parseFloat(due.getText()));
                     pst1.setString(8, ddate.getText());
             
                    pst1.executeUpdate();
                   
                    }catch(Exception ex){
                   Logger.getLogger(drugReg.class.getName()).log(Level.SEVERE, null, ex);
                      }
        
       
                    
        Toolkit tkp = pan.getToolkit();
    PrintJob pjp = tkp.getPrintJob(this, null, null);
    Graphics g = pjp.getGraphics();
    pan.print(g);
    g.dispose();
    pjp.end();
     setVisible(false);
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new report().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel cash;
    private javax.swing.JLabel cell;
    private javax.swing.JLabel cn;
    private javax.swing.JLabel ddate;
    private javax.swing.JLabel due;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JPanel pan;
    private javax.swing.JLabel rr;
    private javax.swing.JTable ttt;
    // End of variables declaration//GEN-END:variables
}
